### ISSUE TITLE
Lista das votações

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/coesao-parlamentar#2]
A API http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/ProposicoesVotadasEmPlenario lista as votações em uma determinada data, e http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/obtervotacaoproposicao pega uma votação específica.

**Comment by fernandobrito** [comment]
Estou trabalhando nisso no momento. A API é muito chatinha.
- Pego as proposições em ListarProposicoesVotadasEmPlenario. Isso me dá a proposição com ID

Beleza! Acontece que para pegar a votação, eu preciso passar "tipo", "numero" e "ano"
- Vou em ObterProposicaoPorID, passo o ID e pego o "tipo", o "numero" e "ano" com o ID que eu tenho

Mas hey! Para pegar a votação eu preciso do "tipo" em sigla, e a chamada anterior me retorna um string completo.
- Vou ter que ir em ListarSiglasTipoProposicao :(

Why you no have ObterVotosPorID? :(

**Comment by fernandobrito** [comment]
Ah não, mentira. ObterProposicaoPorID me retorna a sigla mesmo :D.

**Comment by fernandobrito** [comment]
http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterVotacaoProposicao?tipo=PL&numero=4580&ano=1990

"N&#227;o foi poss&#237;vel obter as orienta&#231;&#245;es de Bancadas."

Todas as proposições antigas (até ~1997) retornam esse erro :(
Foda que talvez eles tenham os votos, mas por causa do erro a gente não consegue ver.

**Comment by fernandobrito** [comment]
@vitorbaptista a gente commita direto o código, ou manda pull request? :P 

Acho que a gente já pode ir pensando nos detalhes de como vamos construir o grafo.

**Comment by vitorbaptista** [comment]
Pode commitar direto. Depois vou criar a estrutura da visualização pra
começarmos a ver. Mas gostaria de ter os dados antes (pelo menos esses).
